persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 1883 0.0.0.0

# Учебный режим для ИЗОЛИРОВАННОЙ лабораторной сети/VLAN.
# Перед подключением к общей сети или Интернету обязательно:
# 1) установить allow_anonymous false;
# 2) подключить password_file;
# 3) настроить ACL;
# 4) при необходимости включить TLS.
allow_anonymous true
